"use client";

import { useState } from "react";
import { Cookie, ArrowLeftRight, Copy, Download, Trash2, FileJson, FileText } from "lucide-react";
import * as XLSX from "xlsx";
import clsx from "clsx";
import { ToolHeader } from "@/components/ToolHeader";

export default function CookieConverter() {
  const [input, setInput] = useState("");
  const [output, setOutput] = useState("");
  const [mode, setMode] = useState<"netscape2json" | "json2netscape">("netscape2json");
  const [error, setError] = useState("");

  const convert = () => {
    setError("");
    if (!input.trim()) return;

    try {
      if (mode === "netscape2json") {
        // Netscape to JSON
        const lines = input.split("\n").filter(l => l.trim() && !l.startsWith("#"));
        const cookies = lines.map(line => {
          const parts = line.split("\t");
          if (parts.length < 7) return null;
          return {
            domain: parts[0],
            flag: parts[1] === "TRUE",
            path: parts[2],
            secure: parts[3] === "TRUE",
            expiration: parts[4],
            name: parts[5],
            value: parts[6]
          };
        }).filter(c => c !== null);
        
        if (cookies.length === 0) {
            setError("无法解析 Netscape 格式，请检查输入 (通常以 Tab 分隔)");
            return;
        }
        setOutput(JSON.stringify(cookies, null, 2));
      } else {
        // JSON to Netscape
        let cookies;
        try {
            cookies = JSON.parse(input);
        } catch (e) {
            setError("无效的 JSON 格式");
            return;
        }

        if (!Array.isArray(cookies)) {
            cookies = [cookies];
        }

        const header = "# Netscape HTTP Cookie File\n# This file is generated by Cookie Converter\n\n";
        const body = cookies.map((c: any) => {
            const domain = c.domain || "";
            const flag = c.flag || c.httpOnly ? "TRUE" : "FALSE"; // Netscape flag usually refers to include subdomains? Actually 2nd col is 'flag - TRUE if is a domain cookie'. 
            // Standard Netscape: domain, flag, path, secure, expiration, name, value
            // Let's try to map common fields
            const includeSubdomains = c.domain && c.domain.startsWith(".") ? "TRUE" : "FALSE";
            const path = c.path || "/";
            const secure = c.secure ? "TRUE" : "FALSE";
            const expiration = c.expirationDate || c.expiration || Math.round(Date.now() / 1000 + 31536000);
            const name = c.name || "";
            const value = c.value || "";
            
            return [domain, includeSubdomains, path, secure, expiration, name, value].join("\t");
        }).join("\n");

        setOutput(header + body);
      }
    } catch (e: any) {
      setError(`转换失败: ${e.message}`);
    }
  };

  const copyToClipboard = () => {
    navigator.clipboard.writeText(output);
  };

  const exportExcel = () => {
    if (!output) return;
    // For Excel, we might want a structured table regardless of output format
    let data: any[] = [];
    
    try {
        if (mode === "netscape2json") {
            data = JSON.parse(output);
        } else {
            // Parse the generated Netscape back to objects for Excel
            const lines = output.split("\n").filter(l => l.trim() && !l.startsWith("#"));
            data = lines.map(line => {
                const parts = line.split("\t");
                return {
                    domain: parts[0],
                    flag: parts[1],
                    path: parts[2],
                    secure: parts[3],
                    expiration: parts[4],
                    name: parts[5],
                    value: parts[6]
                };
            });
        }
    } catch {
        // Fallback
        data = [{ content: output }];
    }

    const ws = XLSX.utils.json_to_sheet(data);
    const wb = XLSX.utils.book_new();
    XLSX.utils.book_append_sheet(wb, ws, "Cookies");
    XLSX.writeFile(wb, `cookies_${new Date().getTime()}.xlsx`);
  };

  return (
    <div className="max-w-[1600px] mx-auto p-6 space-y-6">
      <ToolHeader
        title="Cookie 格式转换"
        description="Netscape 与 JSON 格式 Cookie 互转，支持批量处理与格式化。"
        icon={Cookie}
      />

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-6 h-[600px]">
        {/* Input */}
        <div className="flex flex-col gap-4">
          <div className="flex justify-between items-center">
            <label className="font-medium text-sm">输入数据</label>
            <div className="flex gap-2 bg-neutral-100 dark:bg-neutral-800 p-1 rounded-lg">
              <button
                onClick={() => setMode("netscape2json")}
                className={clsx(
                  "px-3 py-1 text-xs rounded-md transition-all flex items-center gap-2",
                  mode === "netscape2json" ? "bg-white dark:bg-neutral-700 shadow-sm" : "text-neutral-500"
                )}
              >
                <FileText size={14} /> Netscape
                <ArrowLeftRight size={12} />
                <FileJson size={14} /> JSON
              </button>
              <button
                onClick={() => setMode("json2netscape")}
                className={clsx(
                  "px-3 py-1 text-xs rounded-md transition-all flex items-center gap-2",
                  mode === "json2netscape" ? "bg-white dark:bg-neutral-700 shadow-sm" : "text-neutral-500"
                )}
              >
                <FileJson size={14} /> JSON
                <ArrowLeftRight size={12} />
                <FileText size={14} /> Netscape
              </button>
            </div>
          </div>
          <textarea
            className="flex-1 p-4 rounded-xl bg-white dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 resize-none font-mono text-xs focus:ring-2 focus:ring-brand outline-none"
            placeholder={mode === "netscape2json" ? ".google.com\tTRUE\t/\tFALSE\t1234567890\tname\tvalue" : '[{"domain": ".google.com", "name": "cookie", "value": "value"}]'}
            value={input}
            onChange={(e) => setInput(e.target.value)}
          />
          <div className="flex gap-2">
            <button
              onClick={convert}
              className="flex-1 py-2 bg-brand text-white rounded-lg hover:opacity-90 transition-opacity"
            >
              开始转换
            </button>
            <button
              onClick={() => { setInput(""); setOutput(""); setError(""); }}
              className="px-4 py-2 border border-neutral-200 dark:border-neutral-800 rounded-lg hover:bg-neutral-50 dark:hover:bg-neutral-800"
            >
              <Trash2 size={18} />
            </button>
          </div>
        </div>

        {/* Output */}
        <div className="flex flex-col gap-4">
          <div className="flex justify-between items-center">
            <label className="font-medium text-sm">转换结果</label>
            <div className="flex gap-2">
              <button
                onClick={exportExcel}
                disabled={!output}
                className="flex items-center gap-1 text-xs px-2 py-1 bg-green-50 text-green-600 rounded hover:bg-green-100 disabled:opacity-50"
              >
                <Download size={14} /> Excel
              </button>
              <button
                onClick={copyToClipboard}
                disabled={!output}
                className="flex items-center gap-1 text-xs px-2 py-1 bg-blue-50 text-blue-600 rounded hover:bg-blue-100 disabled:opacity-50"
              >
                <Copy size={14} /> 复制
              </button>
            </div>
          </div>
          <div className="relative flex-1">
            <textarea
              readOnly
              className={clsx(
                "w-full h-full p-4 rounded-xl bg-neutral-50 dark:bg-neutral-950 border border-neutral-200 dark:border-neutral-800 resize-none font-mono text-xs focus:ring-2 focus:ring-brand outline-none",
                error && "border-red-500 focus:ring-red-500"
              )}
              value={error || output}
            />
          </div>
        </div>
      </div>
    </div>
  );
}
